### ISSUE TITLE
Links in README are broken

### ISSUE THREAD

**Issue by joepin** [cisc3410/0-get-started#2]
Professor,

I think you mentioned this in class, but the instructions for integrating with travis, as well as submission instructions are not in this repo.

As a side note, the link to the class schedule on line 7 of the readme is being interpreted as a [relative link](https://github.com/blog/1395-relative-links-in-markup-files), and thus not working as expected.

**Comment by rivlev** [comment]
Thanks, I fixed the link to the class schedule. The links to the instructions should work; they are in another repository. Please let me know if you can't see them or close this issue if your question is resolved.

**Comment by joepin** [comment]
Looks good to me - thank you!
