### ISSUE TITLE
Is there a link to accept the assignment?

### ISSUE THREAD

**Issue by qingushu** [cisc3410/0-get-started#3]
Professor Levitan
questions are related to homework0.
Is there a link to accept the assignment/ or join this course on GitHub classroom?

After opened travis, I didn't see any organization showed on the left of my page, how can I join to it?

Do I get a private repository automatically or do I need to create one by myself?

**Comment by wenn009** [comment]
click on ‘Homework 0: Get started with Github’ on 
http://www.sci.brooklyn.cuny.edu/~levitan/ai/ai.php?q=schedule 
It will guide you to join the Github classroom

**Comment by rivlev** [comment]
Github classroom will create the private repository for you once you follow the instructions from the link on the schedule. Once you have the repository created, it should show up in travis.
