### ISSUE TITLE
pull request template?

### ISSUE THREAD

**Issue by qingushu** [cisc3410/0-get-started#4]
Professor Levitan,

should I add a file called PULL_REQUEST_TEMPLATE to my repository? or just fill out something in the body of my pull request?

Is there a sample? what should I write on the pull request template?

**Comment by rivlev** [comment]
It's okay, that doesn't apply to this assignment. When a submission does have a template, you will see it when you try to submit a pull request. Just put your name and @rivlev in the pull request.
